AllCops:
  TargetRubyVersion: 2.3

  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop

    - 'vendor/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
Documentation: # Disabling documentation cop
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25
